MODEL: 'bbunet'
ENCODER: 'resnet18'
PRETRAINED_ENCODER_WEIGHTS: 'pretrained_encoders/B13_rn18_moco_0099_ckpt.pth'
CLOUD_COVER_TO_MASK: [1,-1,-1,1]  # one of [1,-1,-1,1], [1,0,-1,1]
MIN_LANDSLIDE_PIXELS: 200
MAX_CLOUD_COVER: 0.2
N_PREPRE_PAIRS: 0.05
N_POSTPRE_PAIRS: 0.05
N_POSTPOST_PAIRS: 0.05
#BANDS: ['B02','B03','B04','B08']
EPOCHS: 100
LR: 0.001
WEIGHT_DECAY: 0.0001
BATCH_SIZE: 64
SCHEDULER: 'exp'
LR_SCHED_EXP_GAMMA: 0.99
LOSS: ['cross_entropy']
LOSS_WEIGHTS: [1.0]
CE_CLASS_WEIGHTS: [5]
FOCAL_TVERSKY_ALPHA: 0.7
FOCAL_TVERSKY_BETA: 0.3
FOCAL_TVERSKY_GAMMA: 2
#CUSTOM_LR: {"encoder":0.0}
#CUSTOM_WEIGHT_DECAY: {"encoder":0.0}