MODEL: 'seifnet'
N_CLASSES: 2
PRETRAINED_ENCODER_WEIGHTS: 'pretrained_encoders/B13_rn18_moco_0099_ckpt.pth'
CLOUD_COVER_TO_MASK: [1,-1,-1,1]  # one of [1,-1,-1,1], [1,0,-1,1]
MIN_LANDSLIDE_PIXELS: 200
MAX_CLOUD_COVER: 0.2
N_PREPRE_PAIRS: 0.05
N_POSTPRE_PAIRS: 0.05
N_POSTPOST_PAIRS: 0.05
#BANDS: ['B02','B03','B04','B08']
EPOCHS: 50
LR: 0.001
WEIGHT_DECAY: 0.01
BATCH_SIZE: 32
SCHEDULER: 'exp'
LR_SCHED_EXP_GAMMA: 0.99
LOSS: ['cross_entropy','dice']
LOSS_WEIGHTS: [0.75,0.25]
CE_CLASS_WEIGHTS: [1,5]
#CUSTOM_LR: {"encoder":0.0}
#CUSTOM_WEIGHT_DECAY: {"encoder":0.0}